### ISSUE TITLE
Set `log_level` to `debug` when rerunning a job with debugging

### ISSUE THREAD

**Issue by xremming** [jdx/mise-action#128]
Not quite sure what variable needs to be read but based on prior experience and a quick glance at the docs this seems possible.

- https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/re-running-workflows-and-jobs
- https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging

Basically I am wishing that when a run fails and you use the "Re-run failed jobs" with "Enable debug logging" it would automatically always set the `log_level` to `debug`.

**Comment by jdx** [comment]
Doh, I should've tested the most recent change myself

**Comment by xremming** [comment]
Classic case of only testing the initial changes and not the ones getting merged.

Would love to write a test case for this but I have no idea how to do that... 🤔 Looks like [debug mode can be enabled with an environment variable](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging) but is there a way to check the output in a nice way. 🤔
