### ISSUE TITLE
not available for actions

### ISSUE THREAD

**Issue by deregtd** [jdx/mise-action#6]
It looks like there's been a v2.0.0 release, but it hasn't made it into the github actions marketplace yet:
https://github.com/marketplace/actions/mise-action

**Comment by jdx** [comment]
done, but what does going into the marketplace actually do?

**Comment by deregtd** [comment]
There's common github org settings that only allow using actions from the marketplace, so you're limiting your audience without having it published there.  (including me :) )

**Comment by jdx** [comment]
ack
